### ISSUE TITLE
Non-merging `mock` behaviour

### ISSUE THREAD

**Issue by wh1t3cAt1k** [userlike/joke#11]
I was hoping that I would be able to drop-in replace `jest.mock` with `joke`'s `mock` function when it accepts a module factory parameter.

```
mock('module', () => ({
    key: value
}));
```

However, my tests started failing. I am not yet sure why, probably because, according to the docs, it **merges** the default `jest.mock` implementation with what I've provided using `Object.assign`.

However, I am looking to completely pass-through to `jest.mock` without merging, but keeping the type safety / refactoring benefits that `joke` brings.

Would this be possible by exposing another function like `mockDirect` or `mockWithoutMerging`?

**Comment by anilanar** [comment]
@wh1t3cAt1k Do you have reproduction or an error message I can look at? There can be many reasons why it's failing. 
Have you tried `mockSome` in those cases?
I can add a `mockDirect`, but I'm really curious what use-case makes it necessary.

BTW, you can fallback to using `jest.mock` until we figure out a solution.

**Comment by wh1t3cAt1k** [comment]
@anilanar I want to reduce noise and get rid of any secret company code, so give me some time to prepare a repro example. 

Basically `joke` sometimes fails because of just one file in the whole repository, which is `configure-store.js` for the Redux layer.

Inside, it assembles and exports the `createStore` result, as well as a couple of store-dependent promise-returning functions. `joke` also fails on any files that have this `configure-store.js` deep in their require stack.

The failure is at the `createStore` call with a "cannot read property 'apply' of undefined` error message.

Which leads me to believe that somehow, `joke` executes the script before applying mocks.

However, `jest.mock` does not produce an error in a similar scenario and is able to mock everything out properly.

Maybe it is a question of error handling during mocking?

**Comment by anilanar** [comment]
@wh1t3cAt1k Yeah I understand.

jest's auto mocking assumes there are no side effects at the top scope. It works as follows:
- it executes the "module"'s code (hopefully no side effects)
- it inspects exports of the module
- generate mocks based on original export types (e.g. jest.fn for function exports, don't touch value exports, jest.fn for the whole prototype of a class export etc).

So having 1 module with side effects in its top scope (such as `configure-store.ts`) is like a virus because it makes every file that is directly or indirectly depending on it a bad module that cannot be auto-mocked.

I'll introduce a `mockAll` just for the sake of completeness. But I'd suggest you to refactor `configure-store` because it'll always be a headache.

**Comment by wh1t3cAt1k** [comment]
@anilanar great catch, and thanks for the explanation. I tried it with jest's automocking and it fails with the same error. 

So to conclude for everyone else, the root cause is:

* `joke` currently always uses jest automocking, even when a factory function is provided to be merged with automock results), which is why it fails in the same places jest's automocking fails.
* Pure `jest.mock()`, on the other hand, when provided with a factory, does not try to execute the module's code.

Also, for the record, I worked around this issue by manually constructing a mock of `configure-store`, which I execute with `jest.mock` in a setup file (`setupFilesAfterEnv`). 

This way, actual `configure-store` is never executed in the test environment.
